.PHONY: clean All

All:
	@echo "----------Building project:[ ejemplo6 - Debug ]----------"
	@cd "ejemplo6" && "$(MAKE)" -f  "ejemplo6.mk"
clean:
	@echo "----------Cleaning project:[ ejemplo6 - Debug ]----------"
	@cd "ejemplo6" && "$(MAKE)" -f  "ejemplo6.mk" clean
